import { generateAiContent } from "@/lib/gemini";
import { GenerateProjectDescriptionBody } from "@/types/ai.types";
import { ApiResponse } from "@/types/api.types";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
    try {
        const body: GenerateProjectDescriptionBody = await req.json();

        const { experienceLevel, jobTitle, techStack } = body;

        if (!experienceLevel || !jobTitle || !techStack)
            return NextResponse.json<ApiResponse>({
                success: false, message: "Missing fields"
            }, { status: 400 });

        const prompt = `
            You are an expert resume writer, ATS optimization specialist, and senior software engineer.
            
            Generate a professional, ATS-friendly project description based on the information below.
            
            Job Title:
            ${jobTitle}
            
            Experience Level:
            ${experienceLevel}
            
            Tech Stack:
            ${techStack}
            
            Rules:
            
            1. Generate ONLY the project description.
            2. Do NOT generate a project name, headings, titles, labels, bullet points, numbering, or explanations.
            3. The description must be between 80 and 120 words.
            4. Create a realistic project that is relevant to the provided job title.
            5. Naturally incorporate the technologies from the provided tech stack.
            6. Describe the project's purpose, key features, technical implementation, and impact.
            7. Use strong action verbs such as Developed, Built, Designed, Implemented, Engineered, Integrated, and Optimized.
            8. Include ATS-friendly technical keywords.
            9. Do NOT use first-person pronouns such as I, me, or my.
            10. Make the project description sound like a real production-level project completed by a professional developer.
            11. Adapt the complexity of the project according to the experience level:
                - Fresher: Academic or portfolio-level project with practical features.
                - Mid-Level: Business-oriented application with advanced functionality.
                - Senior-Level: Scalable enterprise-grade solution involving architecture, performance optimization, and best practices.
            12. Return plain text only.
            13. Do not mention that the project was generated by AI.
            
            Output:
            Return ONLY the project description text.
            `;

        const result = await generateAiContent(prompt);

        const projectDescription = result;


        return NextResponse.json<ApiResponse>({
            success: true, message: "projectDescription created", data: {
                projectDescription
            }
        }, {
            status: 201
        })

    } catch (error) {
        console.log("error in projectDescription generation api", error);
        return NextResponse.json<ApiResponse>(
            {
                success: false,
                message: "Something went wrong",
            },
            { status: 500 }
        );
    }
}